"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 5.0.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#Посилається на базовий каталог і вказує на верхню ієрархію будь-якого проекту Django.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#Служить ключовим компонентом для захисту підписаних даних, зокрема для криптографічного підпису та підписання файлів cookie сеансу. 
SECRET_KEY = 'django-insecure-tjxw912gc_&ghs#5inkjvkax)w--oh4kx#-p6l-p2$(!!$wmw^'

# SECURITY WARNING: don't run with debug turned on in production!
#Контролює, чи програма перебуває в режимі налагодження
DEBUG = True

#Використовується для визначення списку дійсних імен хостів/доменів для розгортання.
ALLOWED_HOSTS = []


# Application definition

#Список застосунків, що належать проекту
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

#Класи проміжного ПЗ для обробки запитів/відповідей
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

#Шлях до головного конфігуратора
ROOT_URLCONF = 'mysite.urls'

#Конфігурація механізмів шаблонів
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

#Розташування об’єкта програми WSGI, який є точкою входу для обслуговування веб-запитів Django.
WSGI_APPLICATION = 'mysite.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

#Параметри для підключень до бази даних
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

#Контролює перевірку пароля
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

#Визначає мову додатка за замовчуванням
LANGUAGE_CODE = 'en-us'

#Визначає часову зону проекту за замовчуванням
TIME_ZONE = 'UTC'

#Вказує чи ввмікнена система перекладу Django
USE_I18N = True

#Визначає, чи повинен Django використовувати дату й час з урахуванням часового поясу
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

#Визначає базову URL-адресу для надання статичних файлів
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

#Визначає тип первинного ключа для використання під час створення нової моделі
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
